ci: auto labeler cover all type

diff --git a/.github/workflows/auto-labeler.yml b/.github/workflows/auto-labeler.yml
--- a/.github/workflows/auto-labeler.yml
+++ b/.github/workflows/auto-labeler.yml
@@ -25,9 +25,14 @@ jobs:
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             title="${{ github.event.pull_request.title }}"
             number="${{ github.event.pull_request.number }}"
-          else
+            type="pr"
+          elif [[ "${{ github.event_name }}" == "issue" ]]; then
             title="${{ github.event.issue.title }}"
             number="${{ github.event.issue.number }}"
+            type="issue"
+          else
+            echo "Invalid event type: ${{ github.event_name }}"
+            exit 1
           fi
 
           # Function to parse title and return supported labels
@@ -54,13 +59,15 @@ jobs:
 
           echo "labels=${parsed_labels}" >> $GITHUB_OUTPUT
           echo "number=${number}" >> $GITHUB_OUTPUT
+          echo "type=${type}" >> $GITHUB_OUTPUT
           echo $GITHUB_OUTPUT
 
       - name: Add labels to the PR/issue
         if: steps.extract_labels.outputs.labels != ''
-        run: gh issue edit "$NUMBER" --add-label "$LABELS"
+        run: gh "$TYPE" edit "$NUMBER" --add-label "$LABELS"
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GH_REPO: ${{ github.repository }}
           NUMBER: ${{ steps.extract_labels.outputs.number }}
+          TYPE: ${{ steps.extract_labels.outputs.type }}
           LABELS: ${{ steps.extract_labels.outputs.labels }}
