ci: add new dockerfile-lint workflow.v1

diff --git a/.github/workflows/dockerfile-lint.yml b/.github/workflows/dockerfile-lint.yml
--- a/.github/workflows/dockerfile-lint.yml
+++ b/.github/workflows/dockerfile-lint.yml
@@ -12,4 +12,5 @@ jobs:
     - name: Run Dockerfile lint
       # https://github.com/hadolint/hadolint
       # TODO: find better alternatives?
-      run: docker run --rm -i hadolint/hadolint < Dockerfile
+      # Do no fail the workflow on linter error at initial phase, will update this workflow later
+      run: docker run --rm -i hadolint/hadolint < Dockerfile || true
